export const PROJECTS = [
  {
    name: "Fieldnotes",
    company: "Studio North",
    year: 2026,
    img: "/images/projects/img1.jpg",
    color: "#EFFBFF",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.",
  },
  {
    name: "Redline",
    company: "Apex Motors",
    year: 2026,
    img: "/images/projects/img2.jpg",
    color: "#E6F4EE",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus.",
  },
  {
    name: "Gallery Walk",
    company: "MoCA Foundation",
    year: 2019,
    img: "/images/projects/img3.jpg",
    color: "#FFF2F0",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi morbi tempus iaculis urna.",
  },
  {
    name: "Side Profile",
    company: "Lumen Collective",
    year: 2022,
    img: "/images/projects/img4.jpg",
    color: "#F6E6ED",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Egestas purus viverra accumsan in nisl nisi.",
  },
  {
    name: "Open Mic",
    company: "Soundstage Inc",
    year: 2023,
    img: "/images/projects/img5.jpg",
    color: "#E8F0F6",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Volutpat commodo sed egestas egestas fringilla.",
  },
  {
    name: "Backboard",
    company: "ProPlay Analytics",
    year: 2024,
    img: "/images/projects/img6.jpg",
    color: "#E6F4EE",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam quis nostrud.",
  },
  {
    name: "Afterglow",
    company: "Golden Hour Press",
    year: 2021,
    img: "/images/projects/img7.jpg",
    color: "#FFFCE8",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis aute irure dolor in reprehenderit.",
  },
  {
    name: "Hill House",
    company: "Arc Studio",
    year: 2020,
    img: "/images/projects/img8.jpg",
    color: "#B5D3D9",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Excepteur sint occaecat cupidatat non proident.",
  },
  {
    name: "Low Tide",
    company: "Coastal Watch",
    year: 2018,
    img: "/images/projects/img9.jpg",
    color: "#AEC0C7",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim blandit volutpat maecenas volutpat.",
  },
  {
    name: "Timepiece",
    company: "Hora Design",
    year: 2019,
    img: "/images/projects/img10.jpg",
    color: "#D0E9D1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet venenatis urna cursus eget nunc.",
  },
  {
    name: "Close Focus",
    company: "Flora Labs",
    year: 2022,
    img: "/images/projects/img11.jpg",
    color: "#09527F",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Facilisis magna etiam tempor orci eu lobortis.",
  },
  {
    name: "Airframe",
    company: "SkyBridge Systems",
    year: 2023,
    img: "/images/projects/img12.jpg",
    color: "#55AFDA",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tortor dignissim convallis aenean et tortor.",
  },
  {
    name: "Hardcase",
    company: "Forged Co",
    year: 2024,
    img: "/images/projects/img13.jpg",
    color: "#00AA96",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pharetra et ultrices neque ornare aenean.",
  },
  {
    name: "Deep Red",
    company: "Chromatic Arts",
    year: 2021,
    img: "/images/projects/img14.jpg",
    color: "#a66363",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis vitae et leo duis ut diam quam.",
  },
  {
    name: "Fast Track",
    company: "Dash Logistics",
    year: 2022,
    img: "/images/projects/img15.jpg",
    color: "#e67339",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Leo a diam sollicitudin tempor id eu nisl.",
  },
  {
    name: "Night Shift",
    company: "Nocturn Labs",
    year: 2025,
    img: "/images/projects/img16.jpg",
    color: "#5f7c98",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Viverra vitae congue eu consequat ac felis.",
  },
  {
    name: "Deep Red",
    company: "Chromatic Arts",
    year: 2021,
    img: "/images/projects/img17.jpg",
    color: "#a66363",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis vitae et leo duis ut diam quam.",
  },
  {
    name: "Fast Track",
    company: "Dash Logistics",
    year: 2022,
    img: "/images/projects/img18.jpg",
    color: "#e67339",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Leo a diam sollicitudin tempor id eu nisl.",
  },
  {
    name: "Night Shift",
    company: "Nocturn Labs",
    year: 2025,
    img: "/images/projects/img19.jpg",
    color: "#5f7c98",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Viverra vitae congue eu consequat ac felis.",
  },
  {
    name: "Deep Red",
    company: "Chromatic Arts",
    year: 2021,
    img: "/images/projects/img20.jpg",
    color: "#a66363",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sagittis vitae et leo duis ut diam quam.",
  },
  {
    name: "Fast Track",
    company: "Dash Logistics",
    year: 2022,
    img: "/images/projects/img21.jpg",
    color: "#e67339",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Leo a diam sollicitudin tempor id eu nisl.",
  },
  {
    name: "Night Shift",
    company: "Nocturn Labs",
    year: 2025,
    img: "/images/projects/img23.jpg",
    color: "#5f7c98",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Viverra vitae congue eu consequat ac felis.",
  },
   {
    name: "Fast Track",
    company: "Dash Logistics",
    year: 2022,
    img: "/images/projects/img24.jpg",
    color: "#e67339",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Leo a diam sollicitudin tempor id eu nisl.",
  },
  {
    name: "Night Shift",
    company: "Nocturn Labs",
    year: 2025,
    img: "/images/projects/img25.jpg",
    color: "#5f7c98",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Viverra vitae congue eu consequat ac felis.",
  },
];
