export const PROJECTS = [
  // 1–7: Canadian Tomorrow
  {
    name: "Canadian Tomorrow",
    company: "Canadian Tomorrow",
    year: 2024,
    img: "/images/projects/img1.jpg",
    color: "#EFFBFF",
    description: "The citizenship companion app I wished I had — from paper sketches to a cross-platform product in six weeks.",
    link: "/canadian-tomorrow.html",
  },
  {
    name: "Canadian Tomorrow",
    company: "Canadian Tomorrow",
    year: 2024,
    img: "/images/projects/img2.jpg",
    color: "#E6F4EE",
    description: "The citizenship companion app I wished I had — from paper sketches to a cross-platform product in six weeks.",
    link: "/canadian-tomorrow.html",
  },
  {
    name: "Canadian Tomorrow",
    company: "Canadian Tomorrow",
    year: 2024,
    img: "/images/projects/img3.jpg",
    color: "#FFF2F0",
    description: "The citizenship companion app I wished I had — from paper sketches to a cross-platform product in six weeks.",
    link: "/canadian-tomorrow.html",
  },
  {
    name: "Canadian Tomorrow",
    company: "Canadian Tomorrow",
    year: 2024,
    img: "/images/projects/img4.jpg",
    color: "#F6E6ED",
    description: "The citizenship companion app I wished I had — from paper sketches to a cross-platform product in six weeks.",
    link: "/canadian-tomorrow.html",
  },
  {
    name: "Canadian Tomorrow",
    company: "Canadian Tomorrow",
    year: 2024,
    img: "/images/projects/img5.jpg",
    color: "#E8F0F6",
    description: "The citizenship companion app I wished I had — from paper sketches to a cross-platform product in six weeks.",
    link: "/canadian-tomorrow.html",
  },
  {
    name: "Canadian Tomorrow",
    company: "Canadian Tomorrow",
    year: 2024,
    img: "/images/projects/img6.jpg",
    color: "#E6F4EE",
    description: "The citizenship companion app I wished I had — from paper sketches to a cross-platform product in six weeks.",
    link: "/canadian-tomorrow.html",
  },
  {
    name: "Canadian Tomorrow",
    company: "Canadian Tomorrow",
    year: 2024,
    img: "/images/projects/img7.jpg",
    color: "#FFFCE8",
    description: "The citizenship companion app I wished I had — from paper sketches to a cross-platform product in six weeks.",
    link: "/canadian-tomorrow.html",
  },
  // 8–10: Migrant Wallet
  {
    name: "Migrant Wallet",
    company: "Migrant Wallet",
    year: 2023,
    img: "/images/projects/img8.jpg",
    color: "#B5D3D9",
    description: "From sketches to App Store — a personal finance app helping immigrants see their total assets across currencies.",
    link: "/migrant-wallet.html",
  },
  {
    name: "Migrant Wallet",
    company: "Migrant Wallet",
    year: 2023,
    img: "/images/projects/img9.jpg",
    color: "#AEC0C7",
    description: "From sketches to App Store — a personal finance app helping immigrants see their total assets across currencies.",
    link: "/migrant-wallet.html",
  },
  {
    name: "Migrant Wallet",
    company: "Migrant Wallet",
    year: 2023,
    img: "/images/projects/img10.jpg",
    color: "#D0E9D1",
    description: "From sketches to App Store — a personal finance app helping immigrants see their total assets across currencies.",
    link: "/migrant-wallet.html",
  },
  // 11–13: Comentto
  {
    name: "Comentto",
    company: "Comentto",
    year: 2022,
    img: "/images/projects/img11.jpg",
    color: "#09527F",
    description: "Rebuilding a research management platform from the ground up — design system, survey engine, dashboards, and mobile apps.",
    link: "/comentto.html",
  },
  {
    name: "Comentto",
    company: "Comentto",
    year: 2022,
    img: "/images/projects/img12.jpg",
    color: "#55AFDA",
    description: "Rebuilding a research management platform from the ground up — design system, survey engine, dashboards, and mobile apps.",
    link: "/comentto.html",
  },
  {
    name: "Comentto",
    company: "Comentto",
    year: 2022,
    img: "/images/projects/img13.jpg",
    color: "#00AA96",
    description: "Rebuilding a research management platform from the ground up — design system, survey engine, dashboards, and mobile apps.",
    link: "/comentto.html",
  },
  // 14–16: EA (FIFA 20 Global Series)
  {
    name: "FIFA 20 Global Series",
    company: "EA",
    year: 2020,
    img: "/images/projects/img14.jpg",
    color: "#a66363",
    description: "Rethinking competitiveness in one of the biggest sport video games in the world — redesigning the fan-facing experience.",
    link: "/fifa.html",
  },
  {
    name: "FIFA 20 Global Series",
    company: "EA",
    year: 2020,
    img: "/images/projects/img15.jpg",
    color: "#e67339",
    description: "Rethinking competitiveness in one of the biggest sport video games in the world — redesigning the fan-facing experience.",
    link: "/fifa.html",
  },
  {
    name: "FIFA 20 Global Series",
    company: "EA",
    year: 2020,
    img: "/images/projects/img16.jpg",
    color: "#5f7c98",
    description: "Rethinking competitiveness in one of the biggest sport video games in the world — redesigning the fan-facing experience.",
    link: "/fifa.html",
  },
  // 17–19: Battlefy (Portals)
  {
    name: "Portals",
    company: "Battlefy",
    year: 2020,
    img: "/images/projects/img17.jpg",
    color: "#a66363",
    description: "Turning an agency-style esports operation into a scalable product — delivering client portals 4x faster and making Battlefy profitable.",
    link: "/portals.html",
  },
  {
    name: "Portals",
    company: "Battlefy",
    year: 2020,
    img: "/images/projects/img18.jpg",
    color: "#e67339",
    description: "Turning an agency-style esports operation into a scalable product — delivering client portals 4x faster and making Battlefy profitable.",
    link: "/portals.html",
  },
  {
    name: "Portals",
    company: "Battlefy",
    year: 2020,
    img: "/images/projects/img19.jpg",
    color: "#5f7c98",
    description: "Turning an agency-style esports operation into a scalable product — delivering client portals 4x faster and making Battlefy profitable.",
    link: "/portals.html",
  },
  // 20–22: Rogers
  {
    name: "Retail Sales Platform",
    company: "Rogers",
    year: 2024,
    img: "/images/projects/img20.jpg",
    color: "#a66363",
    description: "Redesigning Canada's largest wireless retail sales system from the ground up — streamlining 150+ screens for 10,000+ agents.",
  },
  {
    name: "Retail Sales Platform",
    company: "Rogers",
    year: 2024,
    img: "/images/projects/img21.jpg",
    color: "#e67339",
    description: "Redesigning Canada's largest wireless retail sales system from the ground up — streamlining 150+ screens for 10,000+ agents.",
  },
  {
    name: "Retail Sales Platform",
    company: "Rogers",
    year: 2024,
    img: "/images/projects/img23.jpg",
    color: "#5f7c98",
    description: "Redesigning Canada's largest wireless retail sales system from the ground up — streamlining 150+ screens for 10,000+ agents.",
  },
  // 23–25: Valence
  {
    name: "Valence",
    company: "Valence",
    year: 2022,
    img: "/images/projects/img24.jpg",
    color: "#e67339",
    description: "Unlocking activation and scalable design — improving onboarding by 30% for Fortune 500 companies like Coca-Cola, Nestle, and Vanguard.",
    link: "/valence.html",
  },
  {
    name: "Valence",
    company: "Valence",
    year: 2022,
    img: "/images/projects/img25.jpg",
    color: "#5f7c98",
    description: "Unlocking activation and scalable design — improving onboarding by 30% for Fortune 500 companies like Coca-Cola, Nestle, and Vanguard.",
    link: "/valence.html",
  },
];
